#!/usr/bin/with-contenv bash
# ==============================================================================
# Community Hass.io Add-ons: AirSonos
# Runs the AirSonos server
# ==============================================================================
# shellcheck disable=SC1091
source /usr/lib/hassio-addons/base.sh

declare -a options

hass.log.info 'Starting the deCONZ server'

if hass.config.true 'xpra'; then
  xpra start --bind-tcp=0.0.0.0:8236 :100
  export DISPLAY=:100
else
  options+=(-platform minimal)
fi

# Non-interactive

# Connect to zigbee adapter
options+=(--auto-connect=1)

if hass.config.has_value 'debug_info'; then
   options+=(--dbg-info=$(hass.config.get 'debug_info'))
else
options+=(--dbg-info=1)
fi

if hass.config.has_value 'debug_aps'; then
   options+=(--dbg-aps=$(hass.config.get 'debug_aps'))
fi

if hass.config.has_value 'debug_zcl'; then
   options+=(--dbg-zcl=$(hass.config.get 'debug_zcl'))
fi

if hass.config.has_value 'debug_zdp'; then
   options+=(--dbg-zdp=$(hass.config.get 'debug_zdp'))
fi

if hass.config.has_value 'debug_otau'; then
   options+=(--dbg-otau=$(hass.config.get 'debug_otau'))
fi

# Bind to a specific interface
if hass.config.has_value 'httpport'; then
    options+=("--http-port=$(hass.config.get 'httpport'))
fi
if hass.config.has_value 'wsport'; then
    options+=("--ws-port=$(hass.config.get 'wsport'))
fi

# Run deCONZ
exec deCONZ "${options[@]}"
